//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaMedica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public decimal CPF { get; set; }
        public string Nome { get; set; }
        public decimal RG { get; set; }
        public string Endereco { get; set; }
        public decimal Telefone { get; set; }
        public string Email { get; set; }
    }
}
